### ISSUE TITLE
Don't support Mac os x

### ISSUE THREAD

**Issue by keta1** [tomtzook/gradle-cmake#6]
from https://github.com/tomtzook/Castle/blob/master/castle.core/src/main/java/com/castle/util/os/KnownOperatingSystem.java#L6

https://github.com/tomtzook/Castle/blob/master/castle.core/src/main/java/com/castle/util/os/KnownOperatingSystem.java#L21

os.name in my drive is `Mac OS x `

![image](https://user-images.githubusercontent.com/41381927/204235122-0ae1ec44-6f21-4f19-b37a-25a4bfe116d8.png)

don't contains max
![image](https://user-images.githubusercontent.com/41381927/204235091-163dfbba-4d96-4aa6-abc6-fd082a9840ac.png)

**Comment by tomtzook** [comment]
Thanks for noticing it and tracing the problem, just a dumb mistake I made.
Uploaded `1.2.2` with a fix.
