### ISSUE TITLE
No interruption of compilation in case of cmake execution errors

### ISSUE THREAD

**Issue by keta1** [tomtzook/gradle-cmake#7]
https://github.com/tomtzook/gradle-cmake/blob/ad215d2b6b77c6fc94ca450cece720743e5b6157/plugin/src/main/java/com/github/tomtzook/gcmake/tasks/CmakeBuildTask.java#L76

maybe u shoule invkoe isIgnoreExitValue?

https://github.com/gradle/gradle/blob/master/subprojects/process-services/src/main/java/org/gradle/process/BaseExecSpec.java#L39

**Comment by tomtzook** [comment]
A bit surprised. Just checked again to make sure, and it does interrupt on error. Can you post the script you use and the output from _gradle_ build task?

**Comment by teble** [comment]
Demo project: [DexKit](https://github.com/LuckyPray/DexKit), Intentionally modify `:dexkit` module source code to make it non-compilable, use `gradle :main:run` get output:

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/33313113/218359008-00dd0c5c-5573-47d7-9a41-3e585e5982e3.png">

**Comment by tomtzook** [comment]
Okay, seems that this behavior is caused by running the task via _Android Studio_. 
Add the following lines to `dexkit/build.gradle`:
```
tasks.clean.dependsOn tasks.cmakeClean
tasks.jar.dependsOn tasks.cmakeBuild
```

This seemed to solve the problem.

Basically, because of the dependency association on `dexkit` by `main`, there exists a dependency on `:dexkit:jar`. So this would add `:dexkit:cmakeBuild` to the dependency tree.

**Comment by keta1** [comment]
> Okay, seems that this behavior is caused by running the task via _Android Studio_. Add the following lines to `dexkit/build.gradle`:
> 
> ```
> tasks.clean.dependsOn tasks.cmakeClean
> tasks.jar.dependsOn tasks.cmakeBuild
> ```
> 
> This seemed to solve the problem.
> 
> Basically, because of the dependency association on `dexkit` by `main`, there exists a dependency on `:dexkit:jar`. So this would add `:dexkit:cmakeBuild` to the dependency tree.

https://github.com/LuckyPray/DexKit/blob/6cded873a85fd37f165a0ddfcd0f6d9242b378d2/main/build.gradle#L45

**Comment by tomtzook** [comment]
I was referring to [this file](https://github.com/LuckyPray/DexKit/blob/master/dexkit/build.gradle). Try adding the two lines in there

**Comment by keta1** [comment]
> I was referring to [this file](https://github.com/LuckyPray/DexKit/blob/master/dexkit/build.gradle). Try adding the two lines in there

the relevant logic in [this file](https://github.com/LuckyPray/DexKit/blob/master/main/build.gradle#L45)
:main:cmakeBuild dependsOn :dexkit:cmakeBuild
:main:jar dependsOn :main:cmakeBuild

**Comment by tomtzook** [comment]
Very well. Instead add
```groovy
tasks.run.dependsOn(tasks.cmakeBuild)
```

Below [that line](https://github.com/LuckyPray/DexKit/blob/6cded873a85fd37f165a0ddfcd0f6d9242b378d2/main/build.gradle#L45)

**Comment by keta1** [comment]
> Very well. Instead add
> 
> ```groovy
> tasks.run.dependsOn(tasks.cmakeBuild)
> ```
> 
> Below [that line](https://github.com/LuckyPray/DexKit/blob/6cded873a85fd37f165a0ddfcd0f6d9242b378d2/main/build.gradle#L45)

Thank you, it did work as expected after this improvement.
Although I still don't understand how it works, I'll check the gradle documentation to find out why

**Comment by tomtzook** [comment]
> Although I still don't understand how it works, I'll check the gradle documentation to find out why

Well, if you run the task `:main:run` from the terminal, you'll see that it does terminate early. The behavior you saw seems to be only when running from _Android Studio Configuration_. At least as far as I saw.
If that is indeed the case, it is likely that it's related to how _Android Studio_ executes the tasks.

**Comment by teble** [comment]
> > Although I still don't understand how it works, I'll check the gradle documentation to find out why
> 
> Well, if you run the task `:main:run` from the terminal, you'll see that it does terminate early. The behavior you saw seems to be only when running from _Android Studio Configuration_. At least as far as I saw. If that is indeed the case, it is likely that it's related to how _Android Studio_ executes the tasks.

Indeed, it seems to be a problem with the gradle that comes with AS. Thank you for your reply.
